import Head from 'next/head'
// import Body from 'next/body'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import 'antd/dist/antd.css';
import { Button, Space } from 'antd';
import 'bootstrap/dist/css/bootstrap.min.css';
import App from './components/slider';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <App/>
    </>
  )
}
